# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f84006534c434b642337946f7a84976c6b37bd5b19139e76638d9339eef61ed86f8da63cf529a3a464b47d6170caca4c30737251ea1f859a741b8d901b18024

test:
  secret_key_base: 0793321db67b2b7f33d5fd0a8f19e227c38fb23c3975acc56dabadb13e1ee9ddb89eed91035885b8a0c56086ded678204ac43758b7773fbb6b271bbef3ea05d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
